name: FabricProxy Actions
on: [push, pull_request]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validation
        uses: gradle/wrapper-validation-action@v3

      - name: JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle
            .gradle/loom-cache
          key: caches-${{ hashFiles('~/.gradle', '.gradle/loom-cache') }}
          restore-keys: |
            caches-

      - name: Build
        run: ./gradlew build

      - name: Upload-Artifact
        uses: actions/upload-artifact@master
        with:
          name: Artifact
          path: build/libs
